"use strict";
let car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car === 'subaru');
console.log("Is car == 'subaru'? I predict True. ");
console.log(car == 'subaru');
console.log("Is car !== 'Honda'? I predict True. ");
console.log(car !== 'Honda');
console.log("Is car.Upper case =='SUBARU'? I predict True. ");
console.log(car.toUpperCase() == 'SUBARU');
console.log("Is car =='SUBARU'? I predict False. ");
console.log(car == 'SUBARU');
